### ISSUE TITLE
Possible issue on page about using isolation frameworks

### ISSUE THREAD

**Issue by MariekeGO** [SkylineCommunications/dataminer-docs#3966]
On the page about [Using_isolation_frameworks](https://docs.dataminer.services/develop/best_practices/Unit_testing/Using_isolation_frameworks.html), a possible issue was spotted by a user:
"Hello, 
While I'm practicing unit testing I had to use `Log(int, int, string)`, but it doesn't work, so I tried it `Log(string, LogType, LogLevel)` and it worked successfully.
So I checked the documentation and I found on the page [Using_isolation_frameworks](https://docs.dataminer.services/develop/best_practices/Unit_testing/Using_isolation_frameworks.html) that the `Log(string, LogType, LogLevel)` calls `Log(int, int, string)`, but I think this is not correct because it didn't work for me. To be more sure, I hovered over the `Log(int, int, string)` function in Visual Studio (see image below) and they recommend not to use `Log(int, int, string)` ."
![Screenshot (31) (002)](https://github.com/user-attachments/assets/e44554b0-b1a6-4bb3-859e-d44dfe4a1441)

@PedroDebevere, could you verify this and adjust this page if needed?

**Comment by PedroDebevere** [comment]
This section is indeed no longer up to date:
_Note that you may have noticed something unusual in this example: In the Rewrite method, we invoke the following overload of the Log method: Log(string, LogType, LogLevel). However, the verify call in the Assert step looks for an invocation of the following overload of Log: Log(int, int, string).

This is because currently the Log(string, LogType, LogLevel) method is defined as an extension method. Even though this extension method extends the SLProtocol interface, it is not part of the interface. However, this method just calls the Log(int, int, string) method internally (which is defined as part of the SLProtocol interface). Therefore, we can verify whether the Log(string, LogType, LogLevel) method was called by checking whether the Log(int, int, string) method was called.

Currently, several extension methods on the SLProtocol interface are defined. For more information about these methods, see NotifyProtocol class and ProtocolExtenders class._

Since DataMiner 10.1.1, these extension methods have now become part of the SLProtocol interface itself so there is no longer a need to perform a verify on another method.  I updated the examples and text.
